force-app/main/default/objects/EventQueue__c/EventQueue__c.object-meta.xml
<CustomObject>
    <label>Event Queue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EventQueue__c/fields/LastErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>LastErrorMessage__c</fullName>
    <label>Last Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/NextAttempt__c.field-meta.xml
<CustomField>
    <fullName>NextAttempt__c</fullName>
    <formula>IF( 
  ISPICKVAL(Status__c, &#39;Queued&#39;), 
  CreatedDate + (Attempts__c / 24 / 60), 
  NULL 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Next Attempt</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EventQueueType__mdt/EventQueueType__mdt.object-meta.xml
<CustomObject>
    <label>Event Queue Type</label>
    <pluralLabel>Event Queue Types</pluralLabel>
</CustomObject>

force-app/main/default/objects/EventQueueType__mdt/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EventQueueIterable.cls
public class EventQueueIterable implements Iterator<EventQueue.Wrapper> {

    private List<EventQueue__c> events;
    private Integer pointer;

    public EventQueueIterable() {
        // Get the latest queued events
        Map<String, Id> queuedEvents = new Map<String, Id>();
        for (AggregateResult queuedEvent : [SELECT Key__c, MAX(Id) Id FROM EventQueue__c WHERE Status__c = 'Queued' AND NextAttempt__c <= :Datetime.now() GROUP BY Key__c ORDER BY MIN(NextAttempt__c), MIN(Id) ASC LIMIT 1000]) {
            queuedEvents.put((String) queuedEvent.get('Key__c'), (Id) queuedEvent.get('Id'));
        }
        // Get the latest events for all keys from above
        Map<String, Id> latestEvents = new Map<String, Id>();
        for (AggregateResult latestEvent : [SELECT Key__c, MAX(Id) Id FROM EventQueue__c WHERE Key__c IN :queuedEvents.keySet() GROUP BY Key__c ORDER BY MIN(CreatedDate), MIN(Id)]) {
            latestEvents.put((String) latestEvent.get('Key__c'), (Id) latestEvent.get('Id'));
        }
        // Set all earlier events for keys to completed
        List<EventQueue__c> eventsToDiscard = [SELECT Id, Status__c FROM EventQueue__c WHERE Key__c IN :latestEvents.keySet() AND Id NOT IN :latestEvents.values() AND (Status__c = 'Queued' OR Status__c = 'Failed') LIMIT 1000];
        for (EventQueue__c eventToDiscard : eventsToDiscard) {
            eventToDiscard.Status__c = 'Completed';
        }
        update eventsToDiscard;
        // Clean up duplicate failures without later queued or completed events
        Map<String, Id> failedEvents = new Map<String, Id>();
        for (AggregateResult failedEvent : [SELECT Key__c, MAX(Id) Id FROM EventQueue__c WHERE Status__c = 'Failed' GROUP BY Key__c ORDER BY MIN(NextAttempt__c), MIN(Id) ASC LIMIT 100]) {
            failedEvents.put((String) failedEvent.get('Key__c'), (Id) failedEvent.get('Id'));
        }
        eventsToDiscard = [SELECT Id, Status__c FROM EventQueue__c WHERE Key__c IN :failedEvents.keySet() AND Id NOT IN :failedEvents.values() AND (Status__c = 'Failed') LIMIT 100];
        for (EventQueue__c eventToDiscard : eventsToDiscard) {
            eventToDiscard.Status__c = 'Completed';
        }
        update eventsToDiscard;
        // Get the latest queued events that are still queued after the cleanup
        queuedEvents = new Map<String, Id>();
        for (AggregateResult queuedEvent : [SELECT Key__c, MAX(Id) Id FROM EventQueue__c WHERE Status__c = 'Queued' AND Key__c IN :latestEvents.keySet() GROUP BY Key__c ORDER BY MIN(NextAttempt__c), MIN(Id) ASC LIMIT 1000]) {
            queuedEvents.put((String) queuedEvent.get('Key__c'), (Id) queuedEvent.get('Id'));
        }
        this.events = [SELECT Name, Status__c, Key__c, Payload__c, LastErrorMessage__c, Attempts__c FROM EventQueue__c WHERE Id IN :queuedEvents.values() ORDER BY Name, Id ASC];
        this.pointer = 0;
    }

    public Boolean hasNext() {
        if (this.pointer >= this.events.size()) {
            return false;
        } else {
            return true;
        }
    }

    public EventQueue.Wrapper next() {
        EventQueueType__mdt eventQueueType = EventQueue.getMetadataByType(this.events[this.pointer].Name);
        EventQueue.Wrapper wrapper = new EventQueue.Wrapper(this.events[this.pointer].Name, eventQueueType.ClassName__c);
        while (wrapper.events.size() < eventQueueType.BatchSize__c && this.hasNext() && wrapper.type == this.events[this.pointer].Name) {
            wrapper.events.add(this.events[this.pointer]);
            this.pointer++;
        }
        return wrapper;
    }

}